services:
  backend:
    build: ./backend
    networks:
      - default
    ports:
      - "${BACKEND_PORT}:3000"
    volumes:
      - ./backend/src:/app/src

networks:
  default:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.25.0.0/16

