services:
  database:
    environment:
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_USER=${DATABASE_USERNAME}
      - POSTGRES_DB=${DATABASE_NAME}
    image: postgres:alpine
    networks:
      - default
    volumes:
      - db-data

  backend:
    environment:
      - SESSION_SECRET=${SESSION_SECRET}
      - DATABASE_HOST=database
      - DATABASE_PORT=5432
      - DATABASE_NAME=${DATABASE_NAME}
      - DATABASE_USERNAME=${DATABASE_USERNAME}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
    build: ./backend
    networks:
      - default
    volumes:
      - ./backend/src:/app/src

  frontend:
    environment:
      - NGINX_HOST=${SERVER_HOST}
      - NGINX_PORT=80
    image: nginx:alpine
    networks:
      - default
    volumes:
      - ./frontend:/usr/share/nginx/html:ro

  proxy:
    environment:
      - SERVER_HOST=${SERVER_HOST}
      - BACKEND_HOST=backend
      - BACKEND_PORT=3000
      - FRONTEND_HOST=frontend
      - FRONTEND_PORT=80
    image: nginx:alpine
    networks:
      - default
    ports:
      - "${SERVER_PORT}:80"
    volumes:
      - ./proxy/default.conf:/etc/nginx/templates/default.conf.template:ro

networks:
  default:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.16.0.0/16

volumes:
  db-data:
