services:
  database:
    environment:
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_USER=${DATABASE_USERNAME}
      - POSTGRES_DB=${DATABASE_NAME}
    image: postgres:alpine
    networks:
      - default
    volumes:
      - db-data

  backend:
    environment:
      - HOST=${BACKEND_HOST}
      - PORT=${BACKEND_PORT}
      - DATABASE_HOST=database
      - DATABASE_PORT=5432
      - DATABASE_NAME=${DATABASE_NAME}
      - DATABASE_USERNAME=${DATABASE_USERNAME}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
    build: ./backend
    networks:
      - default
    ports:
      - "${BACKEND_PORT}:3000"
    volumes:
      - ./backend/src:/app/src

networks:
  default:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.25.0.0/16

volumes:
  db-data:
